cpu_saturation:
  - cluster: staging-us
    app: api-gateway
    infoThreshold: 0.4
    warnThreshold: 0.6
    critThreshold: 0.8
  - cluster: staging-us
    app: payments
    infoThreshold: 0.3
    warnThreshold: 0.5
    critThreshold: 0.7

mem_saturation:
  - cluster: staging-us
    app: api-gateway
    warnThreshold: 0.85
    critThreshold: 0.95

isalive:
  - cluster: staging-us
    app: api-gateway
    forDuration: "3m"
  - cluster: staging-us
    app: payments
    forDuration: "5m"
