{{- $chunks := chunk 100 ($.Values.mariadb_traffic_qps_high | default list) }}
{{- range $chunkIndex, $rows := $chunks }}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ $.Release.Name }}-mariadb-traffic-qps-high-{{ add1 $chunkIndex }}
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  groups:
    - name: mariadb-traffic-qps-high
      rules:
        {{- $common := $.Values._common | default dict }}
        {{- range $rows }}
        {{- $row := merge . $common }}
        - alert: MariadbTrafficQpsHigh_MaxQps
          expr: rate(mysql_global_status_questions{namespace="{{ $row.namespace }}"}[5m]) > {{ $row.max_qps }}
          for: 5m
          labels:
            severity: warning
            owner: "{{ $row.owner }}"
            namespace: "{{ $row.namespace }}"
          annotations:
            summary: "MariadbTrafficQpsHigh_MaxQps triggered on {{ $row.owner }}"
        {{- end }}
{{- end }}
