{{- $chunks := chunk 100 ($.Values.mariadb_traffic_network_receive | default list) }}
{{- range $chunkIndex, $rows := $chunks }}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ $.Release.Name }}-mariadb-traffic-network-receive-1-{{ add1 $chunkIndex }}
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  groups:
    - name: mariadb-traffic-network-receive
      rules:
        {{- $common := $.Values._common | default dict }}
        {{- range $rows }}
        {{- $row := merge . $common }}
        - alert: MariadbTrafficNetworkReceive_WarnBytes
          expr: rate(container_network_receive_bytes_total{namespace="{{ $row.namespace }}"}[5m]) > {{ $row.warn_bytes }}
          for: 5m
          labels:
            severity: warning
            owner: "{{ $row.owner }}"
            namespace: "{{ $row.namespace }}"
          annotations:
            summary: "MariadbTrafficNetworkReceive_WarnBytes triggered on {{ $row.owner }}"
        {{- end }}
{{- end }}
