{{- $chunks := chunk 100 ($.Values.mariadb_saturation_cpu | default list) }}
{{- range $chunkIndex, $rows := $chunks }}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ $.Release.Name }}-mariadb-saturation-cpu-1-{{ add1 $chunkIndex }}
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  groups:
    - name: mariadb-saturation-cpu
      rules:
        {{- $common := $.Values._common | default dict }}
        {{- range $rows }}
        {{- $row := merge . $common }}
        - alert: MariadbSaturationCpu_WarnPct
          expr: (rate(container_cpu_usage_seconds_total{namespace="{{ $row.namespace }}"}[5m]) / on(namespace, pod) kube_pod_container_resource_requests{namespace="{{ $row.namespace }}", resource="cpu"}) * 100 > {{ $row.warn_pct }}
          for: 5m
          labels:
            severity: warning
            owner: "{{ $row.owner }}"
            namespace: "{{ $row.namespace }}"
          annotations:
            summary: "MariadbSaturationCpu_WarnPct triggered on {{ $row.owner }}"
        - alert: MariadbSaturationCpu_CriticalPct
          expr: (rate(container_cpu_usage_seconds_total{namespace="{{ $row.namespace }}"}[5m]) / on(namespace, pod) kube_pod_container_resource_requests{namespace="{{ $row.namespace }}", resource="cpu"}) * 100 > {{ $row.critical_pct }}
          for: 5m
          labels:
            severity: critical
            owner: "{{ $row.owner }}"
            namespace: "{{ $row.namespace }}"
          annotations:
            summary: "MariadbSaturationCpu_CriticalPct triggered on {{ $row.owner }}"
        {{- end }}
{{- end }}
