services:
  proxy:
    image: alpine/socat
    command: TCP-LISTEN:12014,fork,reuseaddr TCP:192.168.58.2:30080
    ports:
      - "127.0.0.1:12014:12014"
    networks:
      - minikube
    restart: unless-stopped

networks:
  minikube:
    external: true
