apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: rulemgmt
build:
  artifacts:
    - image: rulemgmt
      docker:
        dockerfile: Dockerfile
  local:
    push: false
    useBuildkit: true
deploy:
  helm:
    releases:
      - name: jupyterhub
        remoteChart: jupyterhub
        valuesFiles:
          - k8s/jupyterhub-values.yaml
          - k8s/dev-values.yaml
        namespace: default
        version: 4.3.5
        setValueTemplates:
          singleuser.image.name: '{{.IMAGE_REPO_rulemgmt}}'
          singleuser.image.tag: '{{.IMAGE_TAG_rulemgmt}}'
          singleuser.image.pullPolicy: IfNotPresent
        repo: https://hub.jupyter.org/helm-chart/
  kubectl:
    defaultNamespace: default
