apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: rulemgmt
build:
  artifacts:
    - image: rulemgmt
      docker:
        dockerfile: Dockerfile
  local:
    push: false
    useBuildkit: true
deploy:
  kubeContext: minikube
  helm:
    releases:
      - name: gitea
        remoteChart: gitea
        valuesFiles:
          - k8s/gitea-values.yaml
        namespace: default
        version: 12.6.0
        upgradeOnChange: true
        repo: https://dl.gitea.com/charts/
      - name: jupyterhub
        remoteChart: jupyterhub
        valuesFiles:
          - k8s/jupyterhub-values.yaml
          - k8s/dev-values.yaml
        namespace: default
        version: 4.3.5
        upgradeOnChange: true
        setValueTemplates:
          singleuser.image.name: '{{.IMAGE_REPO_rulemgmt}}'
          singleuser.image.tag: '{{.IMAGE_TAG_rulemgmt}}'
          singleuser.image.pullPolicy: Never
        repo: https://hub.jupyter.org/helm-chart/
