group: mariadb_saturation_cpu

columns:
  warn_pct: {type: number, default: 80, description: CPU usage warning (%)}
  critical_pct: {type: number, default: 95, description: CPU usage critical (%)}

rules:
  - alert: MariadbSaturationCpu_WarnPct
    expr: (rate(container_cpu_usage_seconds_total{namespace="${namespace}"}[5m]) / on(namespace, pod) kube_pod_container_resource_requests{namespace="${namespace}", resource="cpu"}) * 100 > ${warn_pct}
    for: 5m
    labels:
      severity: warning
      owner: ${owner}
      namespace: ${namespace}
    annotations:
      summary: MariadbSaturationCpu_WarnPct triggered on ${owner}
  - alert: MariadbSaturationCpu_CriticalPct
    expr: (rate(container_cpu_usage_seconds_total{namespace="${namespace}"}[5m]) / on(namespace, pod) kube_pod_container_resource_requests{namespace="${namespace}", resource="cpu"}) * 100 > ${critical_pct}
    for: 5m
    labels:
      severity: critical
      owner: ${owner}
      namespace: ${namespace}
    annotations:
      summary: MariadbSaturationCpu_CriticalPct triggered on ${owner}
