instances:
  - db_name: app-db
    tablespace_name: users
    info: 40
    warn: 60
    critical: 80
    severe: 95
  - db_name: app-db
    tablespace_name: orders
    info: 30
    warn: 50
    critical: 75
    severe: 90
