mariadb_latency:
  - instance_name: mariadb-primary
    namespace: default
    warn_ms: 200
    critical_ms: 500
mariadb_traffic:
  - instance_name: mariadb-primary
    namespace: default
    qps_warn: 10
mariadb_errors:
  - instance_name: mariadb-primary
    namespace: default
    warn_rate: 5
    critical_rate: 20
mariadb_saturation_connections:
  - instance_name: mariadb-primary
    namespace: default
    warn_pct: 70
    critical_pct: 90
