apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: kpi-mem-saturation
spec:
  groups:
  - name: kpi_mem_saturation
    rules:
    {{- range .Values.mem_saturation }}
    - alert: MemSaturationWarn
      expr: (node_memory_Active_bytes{cluster="{{ .cluster }}", app="{{ .app }}"} / node_memory_MemTotal_bytes{cluster="{{ .cluster }}", app="{{ .app }}"}) > {{ .warnThreshold }}
      for: 5m
      labels:
        severity: warning
        cluster: "{{ .cluster }}"
        app: "{{ .app }}"
    - alert: MemSaturationCritical
      expr: (node_memory_Active_bytes{cluster="{{ .cluster }}", app="{{ .app }}"} / node_memory_MemTotal_bytes{cluster="{{ .cluster }}", app="{{ .app }}"}) > {{ .critThreshold }}
      for: 2m
      labels:
        severity: critical
        cluster: "{{ .cluster }}"
        app: "{{ .app }}"
    {{- end }}
